name: Fast API docker build push
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the FastAPI Docker image
      run: docker build -t ${{secrets.DOCKER_LOGIN}}/ggamsi:latest .
      
    - name: Login to docker
      run: docker login --username ${{secrets.DOCKER_LOGIN}} --password ${{secrets.DOCKER_PASSWORD}}

    - name: Push the docker image
      run: docker push ${{secrets.DOCKER_LOGIN}}/ggamsi:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LINUX_HOST }}
          username: ${{ secrets.LINUX_USERNAME }}
          key: ${{ secrets.LINUX_SSH_KEY }}
          port: ${{ secrets.LINUX_SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_LOGIN }}
            docker stop ggamsi
            docker rm ggamsi
            docker rmi ${{ secrets.DOCKER_LOGIN }}/ggamsi:latest
            docker pull ${{ secrets.DOCKER_LOGIN }}/ggamsi:latest
            docker run -d -p 8080:8080 --name ggamsi ${{ secrets.DOCKER_LOGIN }}/ggamsi:latest